# Numpy Basics <hr style = "border:2.5px solid hsla(252, 54%, 28%, 1.00)"></hr>

<b><i>Rica Galagate</i></b>
<br>Computer Engineer</br>

In [55]:
import numpy as np
from scipy import stats
from statistics import multimode

# 1D Array

In [56]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [57]:
np.shape(my_array)

(3,)

# 2D Array

In [58]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.shape(my_array)

(2, 3)

In [60]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
np.shape(my_array.T)

(3, 2)

# Measures of Central Tendency

In [62]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [63]:
np.shape(resistance)

(2, 11)

In [64]:
res_mean = np.nanmean(resistance,axis=1)

In [65]:
res_mean[0]

np.float64(9.399999999999999)

In [66]:
res_mean[1]

np.float64(10.75)

In [67]:
print("Jaguar Mean:" + str((res_mean[0]).round(2)) +' ohms')

Jaguar Mean:9.4 ohms


In [68]:
print("Panther Mean:" + str((res_mean[1]).round(2)) +' ohms')

Panther Mean:10.75 ohms


In [69]:
print(f'Jaguar Mean: {res_mean[0]:.2f} ohms')
print(f'Panther Mean: {res_mean[1]:.2f} ohms')

Jaguar Mean: 9.40 ohms
Panther Mean: 10.75 ohms


In [70]:
res_median = np.nanmedian(resistance,axis=1)
res_median

array([9.8 , 9.55])

In [71]:
print(f'Jaguar Median: {res_median[0]:.2f} ohms')
print(f'Panther Median: {res_median[1]:.2f} ohms')

Jaguar Median: 9.80 ohms
Panther Median: 9.55 ohms


In [73]:
res_mode = stats.mode(resistance,axis=1)
res_mode

ModeResult(mode=array([9.8, 9.1]), count=array([2., 3.]))

In [77]:
jag_res = resistance[0]

print("Jaguar Mode:")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar Mode:
9.8 ohms
10.4 ohms


In [78]:
pan_res = resistance[1]

print("Panther Mode:")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther Mode:
9.1 ohms


# Measures of Variablity

In [79]:
# Jaguar vs Panther
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8],
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [80]:
res_max = np.nanmax(resistance,axis=1)
res_min = np.nanmin(resistance,axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [ ]:
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [82]:
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3 

array([10.45 , 10.625])

In [84]:
IQR = res_Q3-res_Q1
IQR

array([1.05, 1.5 ])

In [87]:
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [89]:
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])